name: "Code analysis"

on:
    pull_request:
    push:

config:
    php-version: "8.2"
    dependencies: "locked"
    operating-system: "ubuntu-latest"

jobs:
    analysis:
        name: "Code analysis"
        runs-on: ${{ config.operating-system }}

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v3"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "pcov"
                  php-version: "${{ config.php-version }}"
                  ini-values: memory_limit=-1
                  tools: composer:v2, cs2pr

            - name: "Cache dependencies"
              uses: "actions/cache@v3"
              with:
                  path: |
                      ~/.composer/cache
                      vendor
                  key: "php-${{ config.php-version }}-${{ config.dependencies }}"
                  restore-keys: "php-${{ config.php-version }}-${{ config.dependencies }}"

            - name: "Install dependencies"
              run:  "composer install --no-interaction --no-progress --no-suggest"

            - name: "PHPStan"
              run:  "vendor/bin/phpstan analyse --error-format=github --level=9 src"

            - name: "PHPMD"
              run:  "vendor/bin/phpmd src text codesize,unusedcode,naming,design,cleancode"

            - name: "PHPCS - PSR12"
              run:  "vendor/bin/phpcs -ns --report=summary --extensions=php --standard=PSR12 src"
            
            - name: "PHPCS - DocBlocks"
              run:  "vendor/bin/phpcs src --standard=Squiz --sniffs=Squiz.Commenting.FunctionComment,Squiz.Commenting.FunctionCommentThrowTag,Squiz.Commenting.ClassComment,Squiz.Commenting.VariableComment"
            
            - name: "PHP 7.4 Compatibility"
              run:  "vendor/bin/phpcs -p src --standard=PHPCompatibility --runtime-set testVersion 7.4-"

            - name: "Pest tests"
              run:  "vendor/bin/pest --coverage --min=95"
    tests:
        name: "Unit tests"